# golangci-lint configuration
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-blank: true
    # Exclude fs.Parse since flag package calls os.Exit on error
    exclude-functions:
      - (*flag.FlagSet).Parse
  staticcheck:
    checks: ["all", "-SA9003"]  # Disable SA9003 (empty branch) for error handling patterns

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
